### ISSUE TITLE
Time error in sidekiq-cron 

### ISSUE THREAD

**Issue by bhartis007** [floraison/et-orbi#22]
The issue:
 sidekiq-cron is giving following error.

```
2019-09-03T13:53:00.672Z 960 TID-owuukgjt0 ERROR: CRON JOB: /.rvm/gems/ruby-2.2.2@views/gems/sidekiq-cron-0.3.1/lib/sidekiq/cron/job.rb:434:in `<'
2019-09-03T13:53:15.692Z 960 TID-owuukgjt0 ERROR: CRON JOB: comparison of Time with EtOrbi::EoTime failed.
2019-09-03T13:53:15.692Z 960 TID-owuukgjt0 ERROR: CRON JOB: /.rvm/gems/ruby-2.2.2@views/gems/sidekiq-cron-0.3.1/lib/sidekiq/cron/job.rb:434:in `<'
2019-09-03T13:53:30.711Z 960 TID-owuukgjt0 ERROR: CRON JOB: comparison of Time with EtOrbi::EoTime failed

```

**Comment by jmettraux** [comment]
Please paste here or make a gist of the content of your Gemfile.lock.

Thanks in advance.

**Comment by jmettraux** [comment]
@bhartis007 I need to know the content of your Gemfile.lock. Thanks in advance.

**Comment by bhartis007** [comment]
@jmettraux  Please find the content of my Gemfile.lock below.
```
EM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.11.1)
      actionpack (= 4.2.11.1)
      actionview (= 4.2.11.1)
      activejob (= 4.2.11.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.11.1)
      actionview (= 4.2.11.1)
      activesupport (= 4.2.11.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.11.1)
      activesupport (= 4.2.11.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (4.2.11.1)
      activesupport (= 4.2.11.1)
      globalid (>= 0.3.0)
    activemodel (4.2.11.1)
      activesupport (= 4.2.11.1)
      builder (~> 3.1)
    activerecord (4.2.11.1)
      activemodel (= 4.2.11.1)
      activesupport (= 4.2.11.1)
      arel (~> 6.0)
    activesupport (4.2.11.1)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.4)
    bcrypt (3.1.13)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.2.0.4)
      sass (~> 3.2)
    builder (3.2.3)
    byebug (11.0.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    commonjs (0.2.7)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    debug_inspector (0.0.3)
    devise (4.7.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-bootstrap-views (1.1.0)
    erubis (2.7.0)
    execjs (2.7.0)
    ffi (1.11.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.6)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (4.0.0)
      actionpack (>= 4)
      less (~> 2.6.0)
      sprockets (>= 2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    orm_adapter (0.5.0)
    rack (1.6.11)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.11.1)
      actionmailer (= 4.2.11.1)
      actionpack (= 4.2.11.1)
      actionview (= 4.2.11.1)
      activejob (= 4.2.11.1)
      activemodel (= 4.2.11.1)
      activerecord (= 4.2.11.1)
      activesupport (= 4.2.11.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.11.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.9)
      activesupport (>= 4.2.0, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.2.0)
      loofah (~> 2.2, >= 2.2.2)
    railties (4.2.11.1)
      actionpack (= 4.2.11.1)
      activesupport (= 4.2.11.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.3)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    rdoc (4.3.0)
    responders (2.4.1)
      actionpack (>= 4.2.0, < 6.0)
      railties (>= 4.2.0, < 6.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spring (2.1.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.9)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    twitter-bootstrap-rails (3.2.2)
      actionpack (>= 3.1)
      execjs (>= 2.2.2, >= 2.2)
      less-rails (>= 2.5.0)
      railties (>= 3.1)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-sass (~> 3.2.0)
  byebug
  coffee-rails (~> 4.1.0)
  devise
  devise-bootstrap-views
  jbuilder (~> 2.0)
  jquery-rails
  rails (= 4.2.11.1)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  sqlite3 (~> 1.3.7)
  turbolinks
  twitter-bootstrap-rails
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.17.2
```

**Comment by jmettraux** [comment]
@bhartis007 Are you sure it's the Gemfile.lock of the right project? There is no trace of sidekiq-cron in it.

**Comment by bhartis007** [comment]
> @bhartis007 Are you sure it's the Gemfile.lock of the right project? There is no trace of sidekiq-cron in it.

Changed the  Gemfile.lock.

**Comment by jmettraux** [comment]
The relevant bits:
```
  rufus-scheduler (~> 3.4.0)                                                                     
                                                                                                 
    sidekiq-cron (0.3.1)                                                                         
      rufus-scheduler (>= 2.0.24)                                                                
      sidekiq (>= 2.17.3)                                                                        
                                                                                                 
    rufus-scheduler (3.4.2)                                                                      
      et-orbi (~> 1.0)  
```

According to RubyGems, you're using the 2015-08-21 version of [sidekiq-cron](https://rubygems.org/gems/sidekiq-cron/versions), with the 2017-05-24 version of [rufus-scheduler](https://rubygems.org/gems/rufus-scheduler/versions).

Sidekiq-cron hints that it's OK with any version of rufus-scheduler better or equal to 2.0.24, which is bad. Newer versions of sidekiq-cron have better specified dependencies.

The quickest fix for you would be to downgrade rufus-scheduler from 3.4.2 to something like 2.0.24. You can thus still enjoy sidekiq-cron 0.3.1.

Closing since it's not an et-orbi issue, but not closing the conversation if you need further help.

Best regards.
